# Generated by Django 4.0.4 on 2022-05-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=30)),
                ('contrasenia', models.TextField(max_length=20)),
                ('rol', models.TextField(default='usuario', max_length=20)),
                ('fecha_nac', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=30)),
                ('valor', models.IntegerField()),
                ('estado', models.TextField(default='espera')),
                ('valoracion', models.IntegerField(default=0)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/')),
                ('descripcion', models.TextField(default='Sin descripcion')),
                ('presentacion', models.TextField(default='Molido')),
                ('sabor', models.TextField(default='Chocolate')),
                ('tueste', models.TextField(default='Medio')),
                ('beneficio', models.TextField(default='Natural')),
                ('variedad', models.TextField(default='Borbón')),
                ('cantidad', models.IntegerField(default=1)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIFruitCoffee.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('num_tarjeta', models.TextField(max_length=16, primary_key=True, serialize=False)),
                ('codigo', models.TextField(max_length=3)),
                ('fecha_venc', models.DateField()),
                ('nombre', models.TextField(max_length=30)),
                ('saldo', models.IntegerField(default=0)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIFruitCoffee.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIFruitCoffee.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIFruitCoffee.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIFruitCoffee.metodopago'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIFruitCoffee.usuario'),
        ),
    ]
