# Generated by Django 4.0.4 on 2022-05-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(default=1, upload_to='imagenes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foto',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
