"""
Django settings for FruitCoffee project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import stripe
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j@noyuc(omg&-olna6a5k1%u0)y=i(%4s^5sk0%yv6#08hl=4-'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

#STATICFILES_DIRS=['C:/Users/Javier Martinez/Desktop/Emprendimiento/FruitCoffee/FruitCoffee/login/templates/static']
#STATICFILES_DIRS=['C:/Users/KEVIN CARMONA/Desktop/FruitCoffee/FruitCoffee/login/templates/static']
#/home/javier159/Escritorio/FruitCoffeeProduction/FruitCoffee/login/templates
STATICFILES_DIRS=['/home/javier159/Escritorio/Semestre 9/FruitCoffeeProduction/FruitCoffee/login/templates/static']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'APIFruitCoffee'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'FruitCoffee.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'APIFruitCoffee.views.context_processor.total_carrito'
                
            ],
        },
    },
]

WSGI_APPLICATION = 'FruitCoffee.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}"""
"""import dj_database_url
from decouple import config
DATABASES={
    'default':dj_database_url.config(
        default=config('DATABASE_URL')
    )
}
"""
DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'der8p2vphdau6d',
            'USER': 'kgoshqlrtseiiw',
            'PASSWORD': '0e7b0882e82de2bf225d2dc96cfc04187b0b319c2f593fb56e94e6a581014d32',
            'HOST': 'ec2-3-234-131-8.compute-1.amazonaws.com',
            'PORT': '5432',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static- files/

MEDIA_ROOT=os.path.join(BASE_DIR,'')
MEDIA_URL='/imagenes/'
#MEDIA_URL='/static/'

#MEDIA_URL = '/imagenes/'
#MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'media')


STATIC_ROOT=os.path.join(BASE_DIR,'staticfiles')
STATIC_URL = '/static/'

STATICFILES_DIRS=(
    os.path.join(BASE_DIR,'static'),
)

STATICFILES_STORAGE='whitenoise.storage.CompressedManifestStaticFilesStorage'
#MEDIA_URL='/login/templates/static/image/'



STRIPE_PUBLIC_KEY = "pk_test_51L48ZPAjsr3vktFFelJ89naj65WfNsGn78yWYL2wpVKA2QqvndtCiCDUm0kgP0ZbwTLfKD5sNBXb1AMLZNPhejhF00IhN4l8A5"
STRIPE_SECRET_KEY = "sk_test_51L48ZPAjsr3vktFFlZX8y4SYQIYSX362BbUqSMl3M57B0gq1dQowNslcXIFknf2ba17Ypk0nmxXILFTWPKqx0qYi00Ssy15sEo"
STRIPE_WEBHOOK_SECRET = ""